runtime: python
env: flex
runtime_config:
    python_version: 3.6
entrypoint: gunicorn -b :$PORT -w 4 -k uvicorn.workers.UvicornWorker main:app --timeout 120

resources:
  memory_gb: 12
  cpu: 2
  disk_size_gb: 30

readiness_check:
  app_start_timeout_sec: 6000